name: 'Deploy to WordPress.org / SVN repository'
description: 'Deploy WordPress Plugin to SVN repository'
author: 'richard-muvirimi'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  svn-username:
    description: 'SVN repository username.'
    required: true
  svn-password:
    description: 'SVN repository password.'
    required: true
  plugin-repository:
    description: 'The svn repository name (slug) of the plugin on WordPress.org. Can be a full url to use a custom repository. Defaults to git repository name if empty. Default empty.'
    default: ""
    type: string
  plugin-zip:
    description: 'Zip file name to generate, "slug" (default) to use the plugin slug, any other text to name it differently, empty to disable. ".zip" is appended automatically.'
    default: 'slug'
    type: string
  plugin-zip-folder:
    description: 'Folder name to use at root of zip, "slug" (default) to use the plugin slug as WordPress expects, any other text to name it differently, empty for no folder.'
    default: 'slug'
    type: string
  plugin-version:
    description: 'Tag for releasing to WordPress, "readme" (default) to read the Stable tag from readme.txt in the working directory root, "tag" to use the pushed git tag (fails on non tag pushes), any other text to use as is. The deploy fails if no version can be determined.'
    default: 'readme'
    type: string
    required: true
  commit-message:
    description: 'Commit message for releasing to WordPress, any custom text to use a custom message, "git" (default) to use the last git commit message. Substitutes ":VERSION" with provided/inferred plugin version.'
    default: 'git'
    type: string
  working-directory:
    description: 'Working directory, defaults to $GITHUB_WORKSPACE if empty. All files in working directory will be committed, except those in "assets-directory" directory. The deploy fails if it does not exist. Default empty.'
    default: ""
    type: string
  assets-directory:
    description: 'Directory containing plugin assets, defaults to ".wordpress-org", set empty to disable. Skipped if it does not exist.'
    default: '.wordpress-org'
    type: string
outputs:
  plugin-zip:
    description: 'Path to generated plugin zip file, if "plugin-zip" was set.'
    value: ${{ steps.deploy-zip.outputs.plugin-zip }}
  plugin-version:
    description: 'The version tag used to commit to "plugin-repository".'
    value: ${{ steps.deploy.outputs.plugin-version }}
  commit-message:
    description: 'The message used to commit to "plugin-repository".'
    value: ${{ steps.deploy.outputs.commit-message }}
runs:
  using: 'composite'
  steps:
    - id: setup
      run: |
        sudo apt update
        sudo apt install -y subversion rsync zip
      shell: bash
    - id: deploy
      env:
        INPUT_SVN_USERNAME: ${{ inputs.svn-username }}
        INPUT_SVN_PASSWORD: ${{ inputs.svn-password }}
        INPUT_PLUGIN_REPOSITORY: ${{ inputs.plugin-repository }}
        INPUT_PLUGIN_VERSION: ${{ inputs.plugin-version }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit-message }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
        INPUT_ASSETS_DIRECTORY: ${{ inputs.assets-directory }}
      run: bash ${{ github.action_path }}/deploy.sh
      shell: bash
    - id: deploy-zip
      if: ${{ inputs.plugin-zip != '' }}
      env:
        INPUT_PLUGIN_ZIP: ${{ inputs.plugin-zip }}
        INPUT_PLUGIN_ZIP_FOLDER: ${{ inputs.plugin-zip-folder }}
        INPUT_PLUGIN_REPOSITORY: ${{ inputs.plugin-repository }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
        INPUT_ASSETS_DIRECTORY: ${{ inputs.assets-directory }}
      run: bash ${{ github.action_path }}/deploy-zip.sh
      shell: bash
